### Pytorch 의 여러가지 함수들

In [1]:
import torch

In [2]:
A = torch.randn(3,3) # Normal Distribution 의 n (nxn 행렬)
B = torch.rand(3,3) # 이건 Uniform Distribution [0,1]
print(A)
print(B)

tensor([[ 0.1750,  0.6715,  0.8926],
        [ 1.2048, -0.7561,  0.3858],
        [ 1.8278, -0.7356,  0.2102]])
tensor([[0.0039, 0.3497, 0.9437],
        [0.5315, 0.8061, 0.7104],
        [0.1813, 0.6204, 0.7493]])


In [3]:
# 함수 안에는 torch 형태로 만들어진 tensor 만 파라미터로 입력될 수 있다
A = torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # lne^1 = 1
print(torch.log10(torch.tensor(100)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째 자리 까지 표현 (반올림 해서 )
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림


tensor([[-0.4007, -0.9278, -2.6494],
        [-0.5715,  1.5430,  0.4590],
        [ 1.6073, -0.3073, -0.2891]])
tensor([[0.4007, 0.9278, 2.6494],
        [0.5715, 1.5430, 0.4590],
        [1.6073, 0.3073, 0.2891]])
tensor([[0.6330, 0.9632, 1.6277],
        [0.7560, 1.2422, 0.6775],
        [1.2678, 0.5543, 0.5377]])
tensor([[0.6698, 0.3954, 0.0707],
        [0.5647, 4.6786, 1.5826],
        [4.9895, 0.7354, 0.7489]])
tensor([[-0.9144, -0.0749,  0.9743],
        [-0.5595,  0.4337, -0.7786],
        [ 0.4746, -1.1800, -1.2410]])
tensor(1.0000)
tensor(2.)
tensor([[-0., -1., -3.],
        [-1.,  2.,  0.],
        [ 2., -0., -0.]])
tensor([[-0.4000, -0.9300, -2.6500],
        [-0.5700,  1.5400,  0.4600],
        [ 1.6100, -0.3100, -0.2900]])
tensor([[-1., -1., -3.],
        [-1.,  1.,  0.],
        [ 1., -1., -1.]])
tensor([[-0., -0., -2.],
        [-0.,  2.,  1.],
        [ 2., -0., -0.]])


In [4]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float 자료형 만약 tensor 와 연산하면 tensor 로 변환해줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6) # <- tensor 와 다른 자료형 연산 가능 => 결과물은 tensor

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)


torch.Tensor

In [5]:
torch.nan # not a anumber
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf((torch.tensor([1,2,torch.inf,3,4]))))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False,  True, False, False])


In [15]:
A = torch.randn(3,4,5)
print(A)
# print(torch.max(A))
#print(torch.max(A, dim=0)) # (3,4) 에서 3(열)에 대해서 비교
#print(torch.max(A, dim=1)) # (3,4) 에서 4(행)에 대해서 비교 1D tensor 로 바꿔버림
#print(torch.max(A, dim=2))
# print(torch.max(A, dim=0, keepdim=True))
# print(torch.max(A, dim=1, keepdim=True)) # 차원을 그대로 유지
# print(torch.argmax(A)) # 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A, dim=2)) # 각 열에서 가장 큰 애가 존재하는 인덱스
# print(torch.argmax(A, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스


tensor([[[ 1.0641, -0.9980,  0.6920,  0.0455,  0.6344],
         [ 0.1636, -1.6442,  1.8894, -1.6691,  0.2871],
         [ 0.0133, -0.5066, -1.0939, -0.3209,  0.1241],
         [-1.0524, -0.1372, -0.3031, -1.0660,  0.5123]],

        [[-0.9846, -0.4059,  1.0333,  2.3959, -0.6527],
         [ 1.0649, -0.9239,  0.7984, -0.6144, -0.5708],
         [-2.1332,  1.1214, -0.2015,  1.5854,  0.9433],
         [-0.8142, -1.6534, -1.0408, -0.5477,  0.6139]],

        [[ 0.8702,  0.3294, -0.4357,  1.7067, -0.7826],
         [ 1.0820, -1.2372,  0.4651, -0.2033, -1.0718],
         [ 0.6420,  1.5154, -0.4514, -0.0525,  1.3669],
         [ 0.5568, -0.1611, -0.6119, -1.3669, -0.4984]]])
tensor([[0, 2, 4, 4],
        [3, 0, 3, 4],
        [3, 0, 1, 0]])


In [21]:
a = torch.randn(6,1)
print(a)
a_sorted = torch.sort(a, dim=0)
print(a_sorted)
a = torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))  # 기능은 같다
print(a.abs())

tensor([[ 0.1477],
        [-0.2246],
        [-0.3723],
        [ 0.4005],
        [ 0.2066],
        [ 0.3862]])
torch.return_types.sort(
values=tensor([[-0.3723],
        [-0.2246],
        [ 0.1477],
        [ 0.2066],
        [ 0.3862],
        [ 0.4005]]),
indices=tensor([[2],
        [1],
        [0],
        [4],
        [5],
        [3]]))
tensor([[-0.6945],
        [-1.0171],
        [ 1.6400],
        [ 0.4626],
        [ 0.5943],
        [-0.2061]])
torch.return_types.sort(
values=tensor([[-1.0171],
        [-0.6945],
        [-0.2061],
        [ 0.4626],
        [ 0.5943],
        [ 1.6400]]),
indices=tensor([[1],
        [0],
        [5],
        [3],
        [4],
        [2]]))
torch.return_types.sort(
values=tensor([[ 1.6400],
        [ 0.5943],
        [ 0.4626],
        [-0.2061],
        [-0.6945],
        [-1.0171]]),
indices=tensor([[2],
        [4],
        [3],
        [5],
        [0],
        [1]]))
tensor(1.6400)
tensor(1.6400)
tensor([[0.6945],
        [1.017

In [28]:
A = torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A, dim=1))
print(torch.sum(A, dim=1, keepdim=True))
print(torch.mean(A))
print(torch.mean(A, dim=1))
print(torch.mean(A, dim=1, keepdim=True))
print(torch.std(A))
print(torch.std(A, dim=1))
print(torch.std(A, dim=1, keepdim=True))
print(torch.var(A))
print(torch.var(A, dim=1))
print(torch.var(A, dim=1, keepdim=True))

tensor([[ 0.0339,  0.2506,  0.2146, -0.4199],
        [-1.7640,  0.0202, -0.3513, -1.4506],
        [-0.7139,  0.0457, -0.5266, -1.1033]])
tensor(-5.7646)
tensor([ 0.0792, -3.5457, -2.2982])
tensor([[ 0.0792],
        [-3.5457],
        [-2.2982]])
tensor(-0.4804)
tensor([ 0.0198, -0.8864, -0.5745])
tensor([[ 0.0198],
        [-0.8864],
        [-0.5745]])
tensor(0.6649)
tensor([0.3081, 0.8557, 0.4782])
tensor([[0.3081],
        [0.8557],
        [0.4782]])
tensor(0.4421)
tensor([0.0949, 0.7323, 0.2287])
tensor([[0.0949],
        [0.7323],
        [0.2287]])


In [32]:
A = torch.randint(1,5,size=(12,))
print(A)
print(A.shape)

B = A.reshape(2,2,3)
print(B)
print(B.shape)
print(B.ndim)

tensor([3, 3, 4, 3, 3, 2, 1, 2, 2, 3, 2, 3])
torch.Size([12])
tensor([[[3, 3, 4],
         [3, 3, 2]],

        [[1, 2, 2],
         [3, 2, 3]]])
torch.Size([2, 2, 3])
3


In [33]:
A = torch.arange(20,)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 행이 4개가 되도록 열의 수를 맞춰준다!
print(A.reshape(2,5,-1).shape)
print(A.reshape(1,-1).shape) # 2차원 행벡터
print(A.reshape(-1,1).shape) # 2차원 열벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([1, 20])
torch.Size([20, 1])


In [38]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,2,1])
print(torch.sum(a*b))

a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose(1,0)@b)  # 1번째 demension 랑 0번째 demension 이랑 transpose
print(a.permute(1,0)@b)    # 0번째에는 1번째를 , 1번째에는 0번째를 가져오겠다 <- permute
print(a.T@b)
print(a.t()@b)

A = torch.randn(4,3,6)
print(A.permute(1,2,0).shape)
print(A.transpose(1,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능


tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([3, 6, 4])
torch.Size([4, 6, 3])


In [40]:
x = torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1,2,:,:,:]  와 동일
print(x[1,...,3,:].shape) # x[1,:,:,3,:] 와 동일

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([3, 4, 6])


In [48]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
C = torch.vstack([A,B]) # v = 0번째 차원
D = torch.hstack([A,B]) # h = 1번째 차원에 쌓는다 ( A, B 사이즈 (2,3,4) 로 추가 해보기  -> 3차원일 때도 0, 1, 번째 차원 고정임 구린듯
E = torch.cat([A,B], dim=0)
F = torch.cat([A,B], dim=1)

print(C)
print(D)
print(E)
print(F)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [52]:
A = torch.randn(1,1,1,3,1,1,1,4,1,1,1)
A.squeeze()
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(dim=(0,2,4,5)).shape)

torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])


In [54]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)  # reshape 으로도 충분히 가능

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [66]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
A = A.unsqueeze(dim=0)
B = B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0) # 차원을 추가 해서 쌓고 싶으면 unsqueeze 로 차원 먼저 늘려 놓는게 필수!
print(C.shape)

torch.Size([2, 3, 4])


In [65]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
C=torch.stack([A,B])
print(C) # unsqueeze 안하고 추가할 수 있는 방법 ( 차원을 추가(default는 dim = 0 ) 해서 쌓아줌)
         # 차원을 추가해서 쌓는 방식이다보니 A,B shape 이 완전히 일치해야 함. concat 은 달라도 쌓을 차원 이외 차원들만 맞으면 됨

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [68]:
A = torch.tensor([[1,2],[3,4]])
B=A # 주소 까지 같이 들어감
B[0,0] = 100

print(A)
print(B)

# 같은 값이지만 다른걸 만들고싶다? -> clone 사용
A = torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0] = 100

print(A)
print(B)


tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])
tensor([[100,   2],
        [  3,   4]])


### @ 에 대해 좀 더 알아보자 ( 3차원 행렬에 대한 내적 연산 )

In [71]:
A = torch.randn(5,7)
B = torch.randn(7,10)

C = A@B
print(C.shape)

A = torch.randn(32,5,7)
B = torch.randn(32,7,10) # 5행 7열 짜리 행렬을 32 (각각) 곱한걸 처리함
C = A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [72]:
A = torch.randn(32,5,7)
B = torch.randn(7,10)

C = A@B
print(C.shape)  # 7x10 자리 행렬을 복제를 해서 구하더라~





torch.Size([32, 5, 10])


### numby <-> torch 왔다갔다 가능

- numpy 에서는 지원 되는데 torch 에서는 지원 안되는 함수들이 있어서 변환하는 과정이 필요
- 특히 그림 그릴 때 많이 사용 ( matplotlib~ )

In [75]:
import numpy as np
import torch

a = np.array([1,2,3])
b = torch.tensor([1,2,3])
A = torch.tensor(a) # A - torch.from_numpy(a)
B=b.numpy() # B = np.array(b)
print(type(A))
print(type(B))



<class 'torch.Tensor'>
<class 'numpy.ndarray'>
