### Pytorch 의 여러가지 함수들

In [2]:
import torch

In [3]:
A = torch.randn(3,3) # Normal Distribution 의 n (nxn 행렬)
B = torch.rand(3,3) # 이건 Uniform Distribution [0,1]
print(A)
print(B)

tensor([[ 0.8010, -0.6262, -0.7666],
        [-0.0398, -0.8924, -0.6409],
        [ 1.2998,  0.8018,  0.1749]])
tensor([[0.2491, 0.0307, 0.6859],
        [0.5170, 0.2977, 0.3969],
        [0.6347, 0.3746, 0.3916]])


In [4]:
# 함수 안에는 torch 형태로 만들어진 tensor 만 파라미터로 입력될 수 있다
A = torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # lne^1 = 1
print(torch.log10(torch.tensor(100)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째 자리 까지 표현 (반올림 해서 )
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림


tensor([[ 1.2208, -1.0398, -1.2982],
        [ 0.0344, -1.4960,  1.0387],
        [-0.1995,  0.7890, -0.5198]])
tensor([[1.2208, 1.0398, 1.2982],
        [0.0344, 1.4960, 1.0387],
        [0.1995, 0.7890, 0.5198]])
tensor([[1.1049, 1.0197, 1.1394],
        [0.1856, 1.2231, 1.0192],
        [0.4467, 0.8883, 0.7210]])
tensor([[3.3899, 0.3535, 0.2730],
        [1.0350, 0.2240, 2.8256],
        [0.8191, 2.2012, 0.5946]])
tensor([[ 0.1995,  0.0390,  0.2610],
        [-3.3683,  0.4028,  0.0380],
        [-1.6119, -0.2370, -0.6543]])
tensor(1.0000)
tensor(2.)
tensor([[ 1., -1., -1.],
        [ 0., -1.,  1.],
        [-0.,  1., -1.]])
tensor([[ 1.2200, -1.0400, -1.3000],
        [ 0.0300, -1.5000,  1.0400],
        [-0.2000,  0.7900, -0.5200]])
tensor([[ 1., -2., -2.],
        [ 0., -2.,  1.],
        [-1.,  0., -1.]])
tensor([[ 2., -1., -1.],
        [ 1., -1.,  2.],
        [-0.,  1., -0.]])


In [9]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float 자료형 만약 tensor 와 연산하면 tensor 로 변환해줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6) # <- tensor 와 다른 자료형 연산 가능 => 결과물은 tensor

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)


torch.Tensor

In [16]:
torch.nan # not a anumber
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf((torch.tensor([1,2,torch.inf,3,4]))))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False,  True, False, False])


In [27]:
A = torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A, dim=0)) # (3,4) 에서 3(열)에 대해서 비교
print(torch.max(A, dim=1)) # (3,4) 에서 4(행)에 대해서 비교 1D tensor 로 바꿔버림
print(torch.max(A, dim=0, keepdim=True))
print(torch.max(A, dim=1, keepdim=True)) # 차원을 그대로 유지
print(torch.argmax(A)) # 가장 큰 값이 존재하는 인덱스
print(torch.argmax(A, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스


tensor([[-0.6243, -0.8116, -0.7354, -1.2361],
        [-1.7427,  0.3682, -0.7586, -0.2814],
        [-0.6425,  0.6566, -0.7613,  1.3410]])
tensor(11)
tensor([0, 2, 0, 2])
tensor([0, 1, 3])
